shallow_clone: true

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

cache:
  - C:\cmake-3.6.1-win32-x86

install:
  - ps: |
      if (![IO.File]::Exists("C:\cmake-3.6.1-win32-x86\bin\cmake.exe")) {
        pushd c:\
        Start-FileDownload 'https://cmake.org/files/v3.6/cmake-3.6.1-win32-x86.zip'
        7z x -y cmake-3.6.1-win32-x86.zip
        popd
      }
  - mkdir build && cd build
  - C:\cmake-3.6.1-win32-x86\bin\cmake .. -DRANGE_V3_NO_HEADER_CHECK=1 -T v140_clang_c2

build:
  project: c:/projects/range-v3/build/ALL_BUILD.vcxproj
  parallel: true
  verbosity: minimal

test_script:
  - C:\cmake-3.6.1-win32-x86\bin\ctest

deploy: off
